version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: minishop-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - minishop-net

  server:
    build: ./server
    container_name: minishop-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/minishop
      - NODE_ENV=production
      - APP_VERSION=1.0.0
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - minishop-net

  client:
    build: ./client
    container_name: minishop-client
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - minishop-net

volumes:
  mongo-data:

networks:
  minishop-net:
    driver: bridge
